### ISSUE TITLE
Is this meant to be an anti-hack

### ISSUE THREAD

**Issue by nathblade16** [Foxboy219512/Blooket-Troll-Hack#1]
??????????????????????????????

**Comment by orangemonkey01** [comment]
no

**Comment by Foxboy219512** [comment]
Yes send it to them it does the opposite of hacks

**Comment by orangemonkey01** [comment]
he means like making them not be able to hack

**Comment by Foxboy219512** [comment]
Ok I can try to work on that tomorrow but what device are they on one and two the thing would have to work through the ip or domain. Unless you can figure out a way to stop console commands or bookmarklets I don’t think this will work.
